### ISSUE TITLE
Multiple schedules for a Shipping Vessel is Allowed Containing Same Set of Dates.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#551]
**Steps to Replicate**
1. Log in as admin
2. Go to freight planning
3. If there are no approved booking, make one
4. Go to freight planning
5. Click on the container info and add a vessel
6. On the schedules of the vessel, make 2 similar record. Same origin, destination, arrival and departure, vessel name, company name. Just adjust the voyage number
7. Save it
8. Schedule with same set of dates are saved

**Actual Result**
A shipping vessel can have multiple schedule for the same set of dates.

![49](https://cloud.githubusercontent.com/assets/9795882/7000181/e924d236-dc4e-11e4-945e-f2587bc7b50b.png)

**Expected Result**
There should be a validation for the vessel name, time and date of the schedule.

**Comment by knarceo** [comment]
At the moment, strict validation will not be applied because of certain vessel schedules that has connecting destinations. eg. Voyage # 123xyz can accomodate Vessel Nagaraya that has 3 different destinations like Cebu, Iloilo and Palawan. System may accept entries with identical information but validation will be a bit loose. The important thing to check is if the voyage number is unique

**Comment by barbacenasmc** [comment]
Alright, this is noted. Thanks.
