### ISSUE TITLE
Container from the first booking has been added on the second booking when the user adds container on different bookings at the same time.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#604]
**Steps to replicate**
1. Open 2 new tabs
2. Create 2 different bookings and add a container for each tabs at the same time.

**Actual Result**
Saved container/s for the booking from the first tab were added on the container of the second tab.

![9 1](https://cloud.githubusercontent.com/assets/9795882/7830528/d1b2313e-0480-11e5-86a0-bd448de60a99.png)
![9 2](https://cloud.githubusercontent.com/assets/9795882/7830529/d4923124-0480-11e5-92af-2be0cc8fc105.png)

**Expected Result**
Only the saved container/s from each own tabs should be added.

**Comment by knarceo** [comment]
Struts limitation, two concurrent requests/response submitted to HTTP Server from two different browser tabs or forms at the same time can't happen because they share the same session. As a result, there might be inconsistencies on the submitted datas.

**Comment by barbacenasmc** [comment]
Hi team, if this is the case, how should we handle this issue? The possibilitie for the user to encounter this issue is high because users might perform multitasking by working on different tabs. Otherwise, we should add it to the list of version 1 limitation and clearly tell it to them to avoid future problems.

**Comment by barbacenasmc** [comment]
This will be added to the list of known bugs for version 1 terminal report.
